trigger:
- main

pool:
  name: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'
- script: |
    cd node
    npm install
  displayName: 'npm install'

- task: Docker@2
  displayName: 'Login to OCIR'
  inputs:
    command: login
    containerRegistry: '$(CONTAINER_REGISTRY)'

- task: Docker@2
  displayName: 'Build & Push DB Image $(Build.BuildNumber)'
  inputs:
    command: buildAndPush
    buildContext: '$(System.DefaultWorkingDirectory)'
    Dockerfile: '$(System.DefaultWorkingDirectory)/Dockerfile-db'
    containerRegistry: '$(CONTAINER_REGISTRY)'
    repository: '$(CONTAINER_REPOSITORY_DB)'
    tags: $(Build.BuildNumber)

- task: Docker@2
  displayName: 'Build & Push Node Image $(Build.BuildNumber)'
  inputs:
    command: buildAndPush
    buildContext: '$(System.DefaultWorkingDirectory)'
    Dockerfile: '$(System.DefaultWorkingDirectory)/Dockerfile-node'
    containerRegistry: '$(CONTAINER_REGISTRY)'
    repository: '$(CONTAINER_REPOSITORY)'
    tags: $(Build.BuildNumber)

- task: KubernetesManifest@0
  displayName: 'Setup secret'
  inputs: 
    action: 'createSecret'
    secretType: 'dockerRegistry'
    secretName: '$(OcirPullSecret)'
    namespace: '$(K8S_NAMESPACE)'
    dockerRegistryEndpoint: '$(CONTAINER_REGISTRY)'
    kubernetesServiceConnection: '$(K8S_CONNECTION_NAME)'

- task: KubernetesManifest@0
  displayName: 'Deploy To K8s Cluster - test container'
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: '$(K8S_CONNECTION_NAME)'
    namespace: '$(K8S_NAMESPACE)'
    manifests: |
      $(System.DefaultWorkingDirectory)/deployment.yaml
      $(System.DefaultWorkingDirectory)/svc.yaml
      $(System.DefaultWorkingDirectory)/nginx-ingress.yaml
    imagePullSecrets: |
      $(OcirPullSecret)
    containers: |
      $(containerImageFullNameForK8sDeploy):$(Build.BuildNumber)
      $(containerDBImageFullNameForK8sDeploy):$(Build.BuildNumber)