trigger:
- main

pool:
  name: default

steps:

- task: PowerShell@2
  displayName: 'Setup ADB yaml'
  inputs:
    targetType: 'inline'
    script: |
      ((Get-Content -path adb/deployment-adb.yaml -Raw) -replace 'ADB_COMPARTMENT_OCID', '$(COMPARTMENT)') | Set-Content -Path adb/deployment-adb.yaml

- task: KubernetesManifest@1
  displayName: 'Deploy ADB'
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: '$(K8S_CONNECTION_NAME)'
    manifests: |
      $(System.DefaultWorkingDirectory)/adb/secrets-adb.yaml
      $(System.DefaultWorkingDirectory)/adb/deployment-adb.yaml

- task: PowerShell@2
  displayName: 'Download Oracle instaclient'
  inputs:
    targetType: 'inline'
    script: |
      wget https://download.oracle.com/otn_software/linux/instantclient/23c/instantclient-basic-linux.x64-23.3.0.0.0.zip

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd adb-job
    npm install
  displayName: 'npm install adb-job'

- script: |
    cd ui
    npm install
  displayName: 'npm install ui'

- script: |
    cd price
    npm install
  displayName: 'npm install price svc'

- script: |
    cd options
    npm install
  displayName: 'npm install options svc'

- task: Docker@2
  displayName: 'Login to OCIR'
  inputs:
    command: login
    containerRegistry: '$(CONTAINER_REGISTRY)'

- task: Docker@2
  displayName: 'Build & Push ADB Job Image $(Build.BuildNumber)'
  inputs:
    command: buildAndPush
    buildContext: '$(System.DefaultWorkingDirectory)'
    Dockerfile: '$(System.DefaultWorkingDirectory)/adb-job/Dockerfile-adb-job'
    containerRegistry: '$(CONTAINER_REGISTRY)'
    repository: '$(CONTAINER_REPOSITORY_ADB_JOB)'
    tags: $(Build.BuildNumber)

- task: Docker@2
  displayName: 'Build & Push UI Image $(Build.BuildNumber)'
  inputs:
    command: buildAndPush
    buildContext: '$(System.DefaultWorkingDirectory)'
    Dockerfile: '$(System.DefaultWorkingDirectory)/ui/Dockerfile-ui'
    containerRegistry: '$(CONTAINER_REGISTRY)'
    repository: '$(CONTAINER_REPOSITORY_UI)'
    tags: $(Build.BuildNumber)

- task: Docker@2
  displayName: 'Build & Push Price Image $(Build.BuildNumber)'
  inputs:
    command: buildAndPush
    buildContext: '$(System.DefaultWorkingDirectory)'
    Dockerfile: '$(System.DefaultWorkingDirectory)/price/Dockerfile-price'
    containerRegistry: '$(CONTAINER_REGISTRY)'
    repository: '$(CONTAINER_REPOSITORY_PRICE)'
    tags: $(Build.BuildNumber)

- task: Docker@2
  displayName: 'Build & Push Options Image $(Build.BuildNumber)'
  inputs:
    command: buildAndPush
    buildContext: '$(System.DefaultWorkingDirectory)'
    Dockerfile: '$(System.DefaultWorkingDirectory)/options/Dockerfile-options'
    containerRegistry: '$(CONTAINER_REGISTRY)'
    repository: '$(CONTAINER_REPOSITORY_OPTIONS)'
    tags: $(Build.BuildNumber)

- task: KubernetesManifest@1
  displayName: 'Setup secret'
  inputs: 
    action: 'createSecret'
    secretType: 'dockerRegistry'
    secretName: 'ocirpullsecret'
    dockerRegistryEndpoint: '$(CONTAINER_REGISTRY)'
    kubernetesServiceConnection: '$(K8S_CONNECTION_NAME)'

- task: PowerShell@2
  displayName: 'Setup OCIR for yamls'
  inputs:
    targetType: 'inline'
    script: |
      ((Get-Content -path $(System.DefaultWorkingDirectory)/ui/deployment-ui.yaml -Raw) -replace 'OCIR/NAMESPACE', '$(OCIR)/$(NAMESPACE)') | Set-Content -Path $(System.DefaultWorkingDirectory)/ui/deployment-ui.yaml
      ((Get-Content -path $(System.DefaultWorkingDirectory)/price/deployment-price.yaml -Raw) -replace 'OCIR/NAMESPACE', '$(OCIR)/$(NAMESPACE)') | Set-Content -Path $(System.DefaultWorkingDirectory)/price/deployment-price.yaml
      ((Get-Content -path $(System.DefaultWorkingDirectory)/options/deployment-options.yaml -Raw) -replace 'OCIR/NAMESPACE', '$(OCIR)/$(NAMESPACE)') | Set-Content -Path $(System.DefaultWorkingDirectory)/options/deployment-options.yaml
      ((Get-Content -path $(System.DefaultWorkingDirectory)/adb-job/deployment-adb-job.yaml -Raw) -replace 'OCIR/NAMESPACE', '$(OCIR)/$(NAMESPACE)') | Set-Content -Path $(System.DefaultWorkingDirectory)/adb-job/deployment-adb-job.yaml

- task: PowerShell@2
  displayName: 'Setup ADB job yaml'
  inputs:
    targetType: 'inline'
    script: |
      ((Get-Content -path adb-job/deployment-adb-job.yaml -Raw) -replace 'ADB_JOB_NAME', 'adb-job-$(Build.BuildId)') | Set-Content -Path adb-job/deployment-adb-job.yaml

- task: KubernetesManifest@1
  displayName: 'Run ADB job in OKE'
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: '$(K8S_CONNECTION_NAME)'
    manifests: |
      $(System.DefaultWorkingDirectory)/adb-job/deployment-adb-job.yaml
    imagePullSecrets: |
      ocirpullsecret
    containers: |
      $(OCIR)/$(CONTAINER_REPOSITORY_ADB_JOB):$(Build.BuildNumber)

- task: KubernetesManifest@1
  displayName: 'Deploy containers to OKE'
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: '$(K8S_CONNECTION_NAME)'
    manifests: |
      $(System.DefaultWorkingDirectory)/ui/deployment-ui.yaml
      $(System.DefaultWorkingDirectory)/price/deployment-price.yaml
      $(System.DefaultWorkingDirectory)/options/deployment-options.yaml
    imagePullSecrets: |
      ocirpullsecret
      ocirpullsecret
      ocirpullsecret
    containers: |
      $(OCIR)/$(NAMESPACE)/azure-test-ui:$(Build.BuildNumber)
      $(OCIR)/$(NAMESPACE)/azure-test-price:$(Build.BuildNumber)
      $(OCIR)/$(NAMESPACE)/azure-test-options:$(Build.BuildNumber)
      $(OCIR)/$(NAMESPACE)/azure-test-adb-job:$(Build.BuildNumber)

- task: KubernetesManifest@1
  displayName: 'Deploy Ingress'
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: '$(K8S_CONNECTION_NAME)'
    namespace: 'ingress-nginx'
    manifests: |
      $(System.DefaultWorkingDirectory)/ingress-nginx/nginx-ingress-1.12.1.yaml

- task: KubernetesManifest@1
  displayName: 'Deploy Ingress Routes to Node app'
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: '$(K8S_CONNECTION_NAME)'
    manifests: |
      $(System.DefaultWorkingDirectory)/ingress-nginx/ui-clusterip.yaml
      $(System.DefaultWorkingDirectory)/ingress-nginx/price-clusterip.yaml
      $(System.DefaultWorkingDirectory)/ingress-nginx/options-clusterip.yaml
      $(System.DefaultWorkingDirectory)/ingress-nginx/ingress-routes.yaml