trigger:
- main

pool:
  name: oci-vm

steps:
- task: Docker@2
  displayName: 'Login to OCIR'
  inputs:
    command: login
    containerRegistry: '$(CONTAINER_REGISTRY)'
- task: Docker@2
  displayName: 'Build & Push Container Image $(Build.BuildNumber)'
  inputs:
    command: buildAndPush
    buildContext: '$(System.DefaultWorkingDirectory)'
    Dockerfile: '$(System.DefaultWorkingDirectory)/Dockerfile'
    containerRegistry: '$(CONTAINER_REGISTRY)'
    repository: '$(CONTAINER_REPOSITORY)'
    tags: 1