apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-db
  labels:
    app: node-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-db
  template:
    metadata:
      labels:
        app: node-db
    spec:
      containers:
      - name: db
        image: fra.ocir.io/frsxwtjslf35/azure-test-db:1
        imagePullPolicy: Always
        ports:
        - containerPort: 1521
        env:
          - name: ORACLE_PWD
            value: "WelcomeFolks123##"
      - name: ui
        image: fra.ocir.io/frsxwtjslf35/azure-test-ui:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      - name: ui
        image: fra.ocir.io/frsxwtjslf35/azure-test-price:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      - name: ui
        image: fra.ocir.io/frsxwtjslf35/azure-test-options:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: fraocirsecret
