apiVersion: batch/v1
kind: Job
metadata:
  name: ADB_JOB_NAME
spec:
  template:
    spec:
      containers:
      - name: ADB_JOB_NAME
        image: fra.ocir.io/frsxwtjslf35/azure-test-adb-job:1
        imagePullPolicy: Always
        volumeMounts:
            - name: secret-volume
              mountPath: /instantclient_23_3/network/admin
        env:
          - name: ATP_PWD
            valueFrom:
              secretKeyRef:
                name: admin-password
                key: admin-password
          - name: CONNECT_STRING
            value: "atp_tp"
      restartPolicy: Never
      imagePullSecrets:
      - name: fraocirsecret
      volumes:
        - name: secret-volume
          secret:
            secretName: instance-wallet
  backoffLimit: 4
  ---
  apiVersion: batch/v1
kind: Job
metadata:
  name: ADB_LOCAL_JOB_NAME
spec:
  template:
    spec:
      containers:
      - name: ADB_LOCAL_JOB_NAME
        image: fra.ocir.io/frsxwtjslf35/azure-test-local-adb-job:1
        imagePullPolicy: Always
        volumeMounts:
            - name: secret-volume
              mountPath: /instantclient_23_3/network/admin
        env:
          - name: ATP_PWD
            value: "WelcomeFolks123##"
          - name: CONNECT_STRING
            value: "localhost:1521/MYATP"
      restartPolicy: Never
      imagePullSecrets:
      - name: fraocirsecret
  backoffLimit: 4