apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: node-test-db
        image: fra.ocir.io/frsxwtjslf35/azure-test-db:1
        imagePullPolicy: Always
        ports:
        - containerPort: 1521
        env:
        - name: ORACLE_PWD
          value: "WelcomeFolks123##"
      - name: node-test-app
        image: fra.ocir.io/frsxwtjslf35/azure-test:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: fraocirsecret
