apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-options-svc
  labels:
    app: node-app-options-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-options-svc
  template:
    metadata:
      labels:
        app: node-app-options-svc
    spec:
      containers:
      - name: db
        image: fra.ocir.io/frsxwtjslf35/azure-test-db:1
        imagePullPolicy: Always
        ports:
        - containerPort: 1521
        env:
          - name: ORACLE_PWD
            value: "WelcomeFolks123##"
      - name: options
        image: fra.ocir.io/frsxwtjslf35/azure-test-options:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
      imagePullSecrets:
      - name: fraocirsecret
