apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-options-svc
  labels:
    app: node-app-options-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-options-svc
  template:
    metadata:
      labels:
        app: node-app-options-svc
    spec:
      containers:
      - name: app
        image: OCIR/NAMESPACE/azure-test-options:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: ATP_PWD
            value: "WelcomeFolks123##"
      initContainers:
      - name: db
        image: container-registry.oracle.com/database/adb-free:latest-23ai
        imagePullPolicy: Always
        restartPolicy: Always
        ports:
        - containerPort: 1521
        env:
          - name: WORKLOAD_TYPE
            value: "ATP"
          - name: ADMIN_PASSWORD
            value: "WelcomeFolks123##"
          - name: WALLET_PASSWORD
            value: "WelcomeFolks123##"
      - name: setup
        image: OCIR/NAMESPACE/azure-test-adb-job:1
        env:
          - name: ATP_PWD
            value: "WelcomeFolks123##"
          - name: CONNECT_STRING
            value: "localhost:1521/MYATP"
          - name: AWAIT
            value: "180000"
