apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-options-svc
  labels:
    app: node-app-options-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-options-svc
  template:
    metadata:
      labels:
        app: node-app-options-svc
    spec:
      containers:
      - name: db
        image: fra.ocir.io/frsxwtjslf35/azure-test-23ai:1
        imagePullPolicy: Always
        ports:
        - containerPort: 1521
        env:
          - name: WORKLOAD_TYPE
            value: "ATP"
          - name: ADMIN_PASSWORD
            value: "WelcomeFolks123##"
          - name: WALLET_PASSWORD
            value: "WelcomeFolks123##"
      - name: app
        image: fra.ocir.io/frsxwtjslf35/azure-test-options:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: ATP_PWD
            value: "WelcomeFolks123##"
      imagePullSecrets:
      - name: fraocirsecret
