apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-options-svc
  labels:
    app: node-app-options-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-options-svc
  template:
    metadata:
      labels:
        app: node-app-options-svc
    spec:
      containers:
      - name: app
        image: fra.ocir.io/frsxwtjslf35/azure-test-options:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: ATP_PWD
            value: "WelcomeFolks123##"
      initContainers:
      - name: db
        image: fra.ocir.io/frsxwtjslf35/azure-test-23ai:1
        imagePullPolicy: Always
        ports:
        - containerPort: 1521
        env:
          - name: WORKLOAD_TYPE
            value: "ATP"
          - name: ADMIN_PASSWORD
            value: "WelcomeFolks123##"
          - name: WALLET_PASSWORD
            value: "WelcomeFolks123##"
        readinessProbe:
          tcpSocket:
            port: 1521
          initialDelaySeconds: 10
      - name: setup
        image: fra.ocir.io/frsxwtjslf35/azure-test-adb-job:1
        env:
          - name: ATP_PWD
            value: "WelcomeFolks123##"
          - name: CONNECT_STRING
            value: "localhost:1521/MYATP"
      imagePullSecrets:
      - name: fraocirsecret
