apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-price-svc
  labels:
    app: node-app-price-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-price-svc
  template:
    metadata:
      labels:
        app: node-app-price-svc
    spec:
      containers:
      - name: app
        image: OCIR/NAMESPACE/azure-test-price:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
            - name: secret-volume
              mountPath: /instantclient_23_3/network/admin
        env:
          - name: ATP_PWD
            valueFrom:
              secretKeyRef:
                name: admin-password
                key: admin-password
      volumes:
        - name: secret-volume
          secret:
            secretName: instance-wallet
