---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oracle-database-operator-oracle-database-operator-manager-rolebinding
  namespace: oracle-database-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oracle-database-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: oracle-database-operator-system
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-password
type: Opaque
data:
  admin-password: V2VsY29tZUZvbGtzMTIzIyE=
---
apiVersion: v1
kind: Secret
metadata:
  name: instance-wallet-password
type: Opaque
data:
  instance-wallet-password: V2VsY29tZUZvbGtzMTIzIyE=
