const oracledb = require('oracledb');

oracledb.initOracleClient({ libDir: '/instantclient_23_3', configDir: '/instantclient_23_3/network/admin/' });
  
async function run() {
  let connection;

  const config = {
    user: "admin",
    password: process.env.ATP_PWD,
    connectString: "atp_tp"
  };

  console.log("atp password:" + config.password);

  try {

    let sql, binds, options, result;
    connection = await oracledb.getConnection(config);
    const stmts = [
      `DROP TABLE PRICE`,

      `CREATE TABLE "PRICE" 
      (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
      "TIER" VARCHAR2(200 BYTE), 
      "PRICE_MO" NUMBER, 
      "USERS" NUMBER, 
      "STORAGE" NUMBER, 
      "SUPPORT" VARCHAR2(1000 BYTE)
      )`,

      `CREATE UNIQUE INDEX "PRICE_PK" ON "PRICE" ("ID")`,

      `CREATE UNIQUE INDEX "PRICE_CON_TIER_UNIQUE" ON "PRICE" ("TIER")`,

      `ALTER TABLE "PRICE" MODIFY ("TIER" NOT NULL ENABLE)`,

      `ALTER TABLE "PRICE" ADD CONSTRAINT "PRICE_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE`,

      `ALTER TABLE "PRICE" ADD CONSTRAINT "PRICE_CON_TIER_UNIQUE" UNIQUE ("TIER") USING INDEX  ENABLE`

    ];

    for (const s of stmts) {
      try {
        await connection.execute(s);
      } catch (e) {
        if (e.errorNum != 942)
          console.error(e);
      }
    }

    sql = `INSERT INTO PRICE (TIER, PRICE_MO, USERS, STORAGE, SUPPORT) VALUES (:1, :2, :3, :4, :5)`;
    binds = [
      ['FREE', 0, 1, 10, 'Email'],
      ['PRO', 10, 15, 200, 'Priority Email'],
      ['ENTERPRISE', 500, 1000, 50000, 'Phone and Email']
    ];

    // For a complete list of options see the documentation.
    options = {
      autoCommit: true,
      // batchErrors: true,  // continue processing even if there are data errors
      bindDefs: [
        { type: oracledb.NUMBER },
        { type: oracledb.STRING, maxSize: 20 }
      ]
    };

    result = await connection.executeMany(sql, binds, options);
    console.log("Number of rows inserted:", result.rowsAffected);

    sql = `SELECT * FROM PRICE`;
    binds = {};
    options = {
      outFormat: oracledb.OUT_FORMAT_OBJECT
    };
    result = await connection.execute(sql, binds, options);
    console.log("Query results: ");
    console.dir(result.rows, { depth: null });

  } catch (err) {
    console.error(err);
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (err) {
        console.error(err);
      }
    }
  }
}

run();