apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-ui
  labels:
    app: node-app-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-ui
  template:
    metadata:
      labels:
        app: node-app-ui
    spec:
      containers:
      - name: ui
        image: fra.ocir.io/frsxwtjslf35/azure-test-ui:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: fraocirsecret
